baseURL = "https://soundz.jakerunzer.com"
languageCode = "en-us"
title = "Soundz"
theme = "coffee"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true

[permalinks]
    post = "/post/:slug"

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
[[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 2

[params]
    description = "An audio fingerprinting project."
    footer = "Project by [Jake Runzer](https://jakerunzer.com)"
